---

- name: install dependency packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - nginx
    - gzip

- name: add connector proxy config
  template:
    src: app.conf.j2
    dest: /etc/nginx/sites-available/app.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for app.conf
  file:
    src: /etc/nginx/sites-available/app.conf
    dest: /etc/nginx/sites-enabled/app.conf
    owner: root
    group: root
    state: link

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

...
